### ISSUE TITLE
Does not detect ">" in pack requires 5.10+

### ISSUE THREAD

**Issue by Tux** [tokuhirom/Perl-MinimumVersion-Fast#13]
$ perl5.8.9 -e'pack"s>",1'
Invalid type '>' in pack at -e line 1.
$ perl5.10.0 -e'pack"s>",1'
$

**Comment by tokuhirom** [comment]
P::MV::F only detects syntax upgrades. It's not supported.
But if you want to write a patch, I'll merge it.

**Comment by Tux** [comment]
PR created
